server:
  port: 9511
spring:
  application:
    name: sb3-mybatis3-bigdata
  config:
     import: conf/mariadb.yml
     # import: conf/mysql-yoga14s.yml
  thymeleaf:
    cache: off
logging:
  level:
    zzjjcc: debug
    org.springframework.transaction: debug
    org.springframework.jdbc: debug
    org.mybatis.spring: debug
    com.alibaba.druid: debug